name        = "Ergopti"
name8       = "hypertxt"
locale      = "fr"
variant     = "Standard"
author      = "Adrien MOYAUX"
description = "Disposition Ergopti, pour une saisie plus rapide de texte."
url         = "https://ergopti.beseven.fr"
geometry    = "ISO"
version     = "1.1.3"

full = '''
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┲━━━━━━━━━━┓
│     │     │     │     │     │     │     │     │     │     │     │     │     ┃          ┃
│     │ 1   │ 2   │ 3   │ 4   │ 5   │ 6   │ 7   │ 8   │ 9   │ 0   │ €   │     ┃ ⌫       ┃
┢━━━━━┷━━┱──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┺━━┳━━━━━━━┫
┃        ┃ È æ │ Y í │ O   │ W   │ B   │ F   │ D   │ L   │ P   │ ?   │ Z   │     ┃       ┃
┃ ↹      ┃   ` │   @ │   œ │   ù │   « │   » │   $ │   = │   + │ ' ? │   ! │*¨   ┃       ┃
┣━━━━━━━━┻┱────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┺┓  ⏎   ┃
┃         ┃ A   │ I   │ E   │ U   │ : · │ V ¦ │ S   │ N ñ │ T   │ R   │ Q   │     ┃      ┃
┃ ⇬       ┃   < │   > │   { │   } │ . : │   | │   ( │   ) │   [ │   ] │   % │*^   ┃      ┃
┣━━━━━━┳━━┹──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┲━━┷━━━━━┻━━━━━━┫
┃      ┃ Ê   │ É   │ À á │ J   │ ; ’ │ K   | M   │ C   │ H   │ G   │ X   ┃               ┃
┃ ⇧    ┃   ^ │   / │   \ │   " │ , ; |   … │   & │   ç │   # │   ~ │   * ┃ ⇧             ┃
┣━━━━━━┻┳━━━━┷━━┳━━┷━━━━┱┴─────┴─────┴─────┴─────┴─────┴─┲━━━┷━━━┳━┷━━━━━╋━━━━━━━┳━━━━━━━┫
┃       ┃       ┃       ┃                                ┃       ┃       ┃       ┃       ┃
┃ Ctrl  ┃ super ┃ Alt   ┃ ␣                              ┃ AltGr ┃ super ┃ menu  ┃ Ctrl  ┃
┗━━━━━━━┻━━━━━━━┻━━━━━━━┹────────────────────────────────┺━━━━━━━┻━━━━━━━┻━━━━━━━┻━━━━━━━┛
'''
[spacebar]
shift       = "-"
altgr       = "_"
altgr_shift = " "