name        = "Ergopti"
name8       = "ergopti"
locale      = "fr"
variant     = "Standard — Analyse"
author      = "Adrien MOYAUX"
description = "Disposition ergonomique optimisée pour le français, l’anglais et le code"
url         = "https://ergopti.fr"
geometry    = "ISO"
version     = "2.2.0"

full = '''
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┲━━━━━━━━━━┓
│     │     │     │     │     │     │     │     │     │     │     │     │     ┃          ┃
│     │ 1   │ 2   │ 3   │ 4   │ 5   │ 6   │ 7   │ 8   │ 9   │ 0   │     │     ┃ ⌫       ┃
┢━━━━━┷━━┱──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┺━━┳━━━━━━━┫
┃        ┃ È æ │ Y í │ O ó │ W   │ B   │ F   │ G ≈ │ H   │ C   │ X × │ Z ‰ │   £ ┃       ┃
┃ ↹      ┃   ` │   @ │   œ │   ù │   « │   » │   ~ │   # │   ç │   * │   % │*¨   ┃       ┃
┣━━━━━━━━┻┱────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┺┓  ⏎   ┃
┃         ┃ A   │ I   │ E   │ U   │ K   │ V ¦ │ S   │ N ñ │ T   │ R   │ Q € │ ! ¡ ┃      ┃
┃ ⇬       ┃   < │   > │   { │   } │   … │   | │   ( │   ) │   [ │   ] │   ' │*^ ! ┃      ┃
┣━━━━━━┳━━┹──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┲━━┷━━━━━┻━━━━━━┫
┃      ┃ Ê   │ : · │ É   │ À á │ J   │ ;   │ M   │ D § │ L ≠ │ P ± │ ? ¿ ┃               ┃
┃ ⇧    ┃   ^ │ . : │   / │   \ │   " │ , ; │   & │   $ │   = │   + │ ’ ? ┃ ⇧             ┃
┣━━━━━━┻┳━━━━┷━━┳━━┷━━━━┱┴─────┴─────┴─────┴─────┴─────┴─┲━━━┷━━━┳━┷━━━━━╋━━━━━━━┳━━━━━━━┫
┃       ┃       ┃       ┃                                ┃       ┃       ┃       ┃       ┃
┃ Ctrl  ┃ super ┃ Alt   ┃ ␣                              ┃ AltGr ┃ super ┃ menu  ┃ Ctrl  ┃
┗━━━━━━━┻━━━━━━━┻━━━━━━━┹────────────────────────────────┺━━━━━━━┻━━━━━━━┻━━━━━━━┻━━━━━━━┛
'''
[spacebar]
shift       = "-"
altgr       = "_"
altgr_shift = " "